name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    # there are a lot of runners that you can choose from. 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done - bye!"
